# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Brand.create(name: "Adidas")
Brand.create(name: "Air Jordan")
Brand.create(name: "Asics")
Brand.create(name: "Balenciaga")
Brand.create(name: "Chanel")
Brand.create(name: "Converse")
Brand.create(name: "Diadora")
Brand.create(name: "Dior")
Brand.create(name: "Gucci")
Brand.create(name: "Li-Ning")
Brand.create(name: "Louis Vuitton")
Brand.create(name: "New Balance")
Brand.create(name: "Nike")
Brand.create(name: "Prada")
Brand.create(name: "Puma")
Brand.create(name: "Reebok")
Brand.create(name: "Saucony")
Brand.create(name: "Under Armour")
Brand.create(name: "Van")

Size.create(size: 7)
Size.create(size: 7.5)
Size.create(size: 8)
Size.create(size: 8.5)
Size.create(size: 9)
Size.create(size: 9.5)
Size.create(size: 10)
Size.create(size: 10.5)
Size.create(size: 11)
Size.create(size: 11.5)
Size.create(size: 12)
Size.create(size: 12.5)
Size.create(size: 13)