# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(name: 'asshikin', email: 'asshikin@ga.com', password: 'password', image_url: 'https://trendingfox.com/wp-content/uploads/2018/12/PhotoGrid_1504641675433-700x700.jpg', admin: true)
User.create(name: 'elise', email: 'elise@ga.com', password: 'password', image_url: 'https://cdn131.picsart.com/278370807021201.jpg?r1024x1024', admin: true)
User.create(name: 'hilmi', email: 'hilmi@ga.com', password: 'password', image_url: 'https://provectapet.com/wp-content/uploads/2017/02/provecta-for-pets-gray-cat_opt.jpg', admin: true)

Brand.create(name: "adidas")
Brand.create(name: "Air Jordan")
Brand.create(name: "Asics")
Brand.create(name: "Balenciaga")
Brand.create(name: "Chanel")
Brand.create(name: "Converse")
Brand.create(name: "Diadora")
Brand.create(name: "Dior")
Brand.create(name: "Gucci")
Brand.create(name: "Li-Ning")
Brand.create(name: "Louis Vuitton")
Brand.create(name: "New Balance")
Brand.create(name: "Nike")
Brand.create(name: "Prada")
Brand.create(name: "Puma")
Brand.create(name: "Reebok")
Brand.create(name: "Saucony")
Brand.create(name: "Under Armour")
Brand.create(name: "Vans")



Size.create(size: 6)
Size.create(size: 6.5)
Size.create(size: 7)
Size.create(size: 7.5)
Size.create(size: 8)
Size.create(size: 8.5)
Size.create(size: 9)
Size.create(size: 9.5)
Size.create(size: 10)
Size.create(size: 10.5)
Size.create(size: 11)
Size.create(size: 11.5)
Size.create(size: 12)
Size.create(size: 12.5)
Size.create(size: 13)


Shoe.create(name: 'Jordan 1 Retro High Satin Black Toe (W)', color: 'BLACK/WHITE-UNIVERSITY RED', release_year: '2019', style: 'CD0461-016', description: 'Jordan Brand adds a twist to a classic with the Air Jordan 1 WMNS Satin “Black Toe”. Jordan is no stranger to adding satin to the Jordan 1. In May of 2018, they released a satin rendition of the “Shattered Backboard” 1 in a similar fashion, revealing that the release would be in women’s sizing. This AJ 1 features classic “Black Toe” color scheme. This design is constructed in a mix of leather and satin construction providing a luxury feel. A metal Wings logo on the heel completes the design. These sneakers released in August of 2019 and retailed for $160.', cost_price: 160, first_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Images/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1566245180&w=1000', second_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Images/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1566245180&w=1000', third_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Images/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1566245180&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Images/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1566245180&w=1000', brand_id: 2, size_id: 11, user_id: 1)
Shoe.create(name: 'Jordan 6 Retro Black Infrared (2019)', color: 'BLACK/INFRARED', release_year: '2019', style: '384664-060', description: 'Make sure your head isn’t in the beam while trying to grab the Jordan 6 Retro Black Infrared (2019). This AJ6 come with a black upper, black midsole plus red accents, and a translucent sole. These sneakers released in February 2019 and retailed for $200. This silhouette is a must cop.', cost_price: 200, first_image_url: 'https://stockx-360.imgix.net/Air-Jordan-6-Retro-Black-Infrared-2019/Images/Air-Jordan-6-Retro-Black-Infrared-2019/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1549058088&w=1000', second_image_url: 'https://stockx-360.imgix.net/Air-Jordan-6-Retro-Black-Infrared-2019/Images/Air-Jordan-6-Retro-Black-Infrared-2019/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1549058088&w=1000', third_image_url: 'https://stockx-360.imgix.net/Air-Jordan-6-Retro-Black-Infrared-2019/Images/Air-Jordan-6-Retro-Black-Infrared-2019/Lv2/img17.jpg?auto=format,compress&q=90&updated_at=1549058088&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Air-Jordan-6-Retro-Black-Infrared-2019/Images/Air-Jordan-6-Retro-Black-Infrared-2019/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1549058088&w=1000', brand_id: 2, size_id: 11, user_id: 1)
Shoe.create(name: 'Air Max 97 Neon Seoul', color: 'Black/Reflect Silver-Blue Lagoon', release_year: '2019', style: 'CI1503-001', description: 'Match the neon lights in the city of Seoul after copping the Air Max 97 Neon Seoul. This AM 97 comes with a black upper plus red, silver, and blue accents, red Nike “Swoosh”, black midsole, and a black sole. These sneakers released in April 2019 and retailed for $200.', cost_price: 200, first_image_url: 'https://stockx-360.imgix.net/Nike-Air-Max-97-Neon-Seoul/Images/Nike-Air-Max-97-Neon-Seoul/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1555622480&w=1000', second_image_url: 'https://stockx-360.imgix.net/Nike-Air-Max-97-Neon-Seoul/Images/Nike-Air-Max-97-Neon-Seoul/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1555622480&w=1000', third_image_url: 'https://stockx-360.imgix.net/Nike-Air-Max-97-Neon-Seoul/Images/Nike-Air-Max-97-Neon-Seoul/Lv2/img18.jpg?auto=format,compress&q=90&updated_at=1555622480&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Nike-Air-Max-97-Neon-Seoul/Images/Nike-Air-Max-97-Neon-Seoul/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1555622480&w=1000', brand_id: 13, size_id: 11, user_id: 1)
Shoe.create(name: 'Kyrie 5 Spongebob Squarepants', color: 'OPTI YELLOW', release_year: '2019', style: 'CJ6951-700', description: 'Nike enlisted Nickelodeon’s SpongeBob SquarePants for another tv-themed collection, including the Nike Kyrie 5 “SpongeBob”. This is Kyrie’s second tv-themed collaboration, the first being a tribute to the sitcom “Friends”. This collection consists of three Kyrie 5 models and two Kyrie Low 2s. All of SpongeBob’s main cast (SpongeBob, Patrick, Squidward, Mr. Krabs, and Sandy) is accounted for in the colorways and design inspiration for this collection. The Kyrie 5 Spongebob features a porous bright-yellow upper with a red and brown sole. The sole was intentionally colored this way to represent his everyday outfit. Nickelodeon logos on the straps, a sponge-inspired Swoosh, and SpongeBob graphics on the insoles completes the design. These sneakers released in August of 2019 retailed for $130.', cost_price: 130, first_image_url: 'https://stockx-360.imgix.net/Nike-Kyrie-5-Spongebob/Images/Nike-Kyrie-5-Spongebob/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1564168668&w=1000', second_image_url: 'https://stockx-360.imgix.net/Nike-Kyrie-5-Spongebob/Images/Nike-Kyrie-5-Spongebob/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1564168668&w=1000', third_image_url: 'https://stockx-360.imgix.net/Nike-Kyrie-5-Spongebob/Images/Nike-Kyrie-5-Spongebob/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1564168668&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Nike-Kyrie-5-Spongebob/Images/Nike-Kyrie-5-Spongebob/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1564168668&w=1000', brand_id: 13, size_id: 11, user_id: 1)
Shoe.create(name: 'Jordan 4 Retro Bred', color: 'Black/Fire Red-Cement Grey-Summit White', release_year: '2019', style: '308497-060', description: 'Looking for a classic sneaker to add to your collection? Then you need to buy the latest and greatest Jordan 4 Retro Bred (2019). This AJ 4, also known as “Black Cement 4,” comes with a black upper plus grey accents, white midsole plus black, white and grey accents, and a red sole. These sneakers released in May 2019 and retailed for $200. Thrive in one of Jordan’s most iconic sneakers ever.', cost_price: 200, first_image_url: 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-Bred-2019/Images/Air-Jordan-4-Retro-Bred-2019/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1555622524&w=1000', second_image_url: 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-Bred-2019/Images/Air-Jordan-4-Retro-Bred-2019/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1555622524&w=1000', third_image_url: 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-Bred-2019/Images/Air-Jordan-4-Retro-Bred-2019/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1555622524&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Air-Jordan-4-Retro-Bred-2019/Images/Air-Jordan-4-Retro-Bred-2019/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1555622524&w=1000', brand_id: 2, size_id: 11, user_id: 1)
Shoe.create(name: 'Kyrie 5 Spongebob Patrick', color: 'LOTUS PINK/UNIVERSITY RED', release_year: '2019', style: 'CJ6951-600', description: 'Nike enlisted Nickelodeon’s SpongeBob SquarePants for another tv-themed collection, including the Nike Kyrie 5 “Patrick Star”. This is Kyrie’s second tv-themed collaboration, the first being a tribute to the sitcom “Friends”. This collection consists of three Kyrie 5 models and two Kyrie Low 2s. All of SpongeBob’s main cast (SpongeBob, Patrick, Squidward, Mr. Krabs, and Sandy) is accounted for in the colorways and design inspiration for this collection. This Kyrie 5 features a bright pink upper with a green and purple sole. The upper has detailing of speckles and texture to represent the surface of a starfish. Nickelodeon logos on the straps, title-font inspired Nike branding on the heel, and Patrick graphics on the insoles completes the design. These sneakers released in August of 2019 retailed for $130.', cost_price: 130, first_image_url: 'https://stockx-360.imgix.net/Nike-Kyrie-5-Spongebob-Patrick/Images/Nike-Kyrie-5-Spongebob-Patrick/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1565638999&w=1000', second_image_url: 'https://stockx-360.imgix.net/Nike-Kyrie-5-Spongebob-Patrick/Images/Nike-Kyrie-5-Spongebob-Patrick/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1565638999&w=1000', third_image_url: 'https://stockx-360.imgix.net/Nike-Kyrie-5-Spongebob-Patrick/Images/Nike-Kyrie-5-Spongebob-Patrick/Lv2/img18.jpg?auto=format,compress&q=90&updated_at=1565638999&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Nike-Kyrie-5-Spongebob-Patrick/Images/Nike-Kyrie-5-Spongebob-Patrick/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1565638999&w=1000', brand_id: 13, size_id: 11, user_id: 1)



Shoe.create(name: 'Jordan 1 Retro High Satin Black Toe (W)', color: 'BLACK/WHITE-UNIVERSITY RED', release_year: '2019', style: 'CD0461-016', description: 'Jordan Brand adds a twist to a classic with the Air Jordan 1 WMNS Satin “Black Toe”. Jordan is no stranger to adding satin to the Jordan 1. In May of 2018, they released a satin rendition of the “Shattered Backboard” 1 in a similar fashion, revealing that the release would be in women’s sizing. This AJ 1 features classic “Black Toe” color scheme. This design is constructed in a mix of leather and satin construction providing a luxury feel. A metal Wings logo on the heel completes the design. These sneakers released in August of 2019 and retailed for $160.', cost_price: 160, first_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Images/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1566245180&w=1000', second_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Images/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1566245180&w=1000', third_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Images/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1566245180&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Images/Air-Jordan-1-Retro-High-Satin-Black-Toe-W/Lv2/img12.jpg?auto=format,compress&q=90&updated_at=1566245180&w=1000', brand_id: 2, size_id: 1, user_id: 2)
Shoe.create(name: 'Jordan 1 Retro High UNC Patent (W)', color: 'OBSIDIAN/BLUE CHILL-WHITE', release_year: '2019', style: 'CD0461-401', description: 'Show some respect to a basketball legend and cop the Jordan 1 Retro High UNC Patent (W). This AJ1 come with a white upper plus blue accents, black Nike “Swoosh”, white midsole, and a blue sole. These sneakers released in February 2019 and retailed for $160. Pay homage to MJ’s college.', cost_price: 160, first_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-UNC-Patent-W/Images/Air-Jordan-1-Retro-High-UNC-Patent-W/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1547848301&w=1000', second_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-UNC-Patent-W/Images/Air-Jordan-1-Retro-High-UNC-Patent-W/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1547848301&w=1000', third_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-UNC-Patent-W/Images/Air-Jordan-1-Retro-High-UNC-Patent-W/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1547848301&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-UNC-Patent-W/Images/Air-Jordan-1-Retro-High-UNC-Patent-W/Lv2/img06.jpg?auto=format,compress&q=90&updated_at=1547848301&w=1000', brand_id: 2, size_id: 1, user_id: 2)
Shoe.create(name: 'Air Force 1 Low Off-White Volt', color: 'VOLT/HYPER JADE-CONE-BLACK', release_year: '2018', style: 'AO4606-700', description: 'Be more lit than a lightning bolt while wearing Nike and Virgil’s Air Force 1 Low Off-White Volt. This AF1 comes with a volt upper, black Nike “Swoosh”, volt midsole, and volt sole. These sneakers released in December 2018 and retailed for $170.', cost_price: 170, first_image_url: 'https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Off-White-Volt/Images/Nike-Air-Force-1-Low-Off-White-Volt/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1544566859&w=1000', second_image_url: 'https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Off-White-Volt/Images/Nike-Air-Force-1-Low-Off-White-Volt/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1544566859&w=1000', third_image_url: 'https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Off-White-Volt/Images/Nike-Air-Force-1-Low-Off-White-Volt/Lv2/img18.jpg?auto=format,compress&q=90&updated_at=1544566859&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Off-White-Volt/Images/Nike-Air-Force-1-Low-Off-White-Volt/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1544566859&w=1000', brand_id: 13, size_id: 1, user_id: 2)
Shoe.create(name: 'adidas NMD Hu Pharrell Solar Pack Mother', color: 'WHITE/PINK/YELLOW', release_year: '2018', style: 'BB9531', description: 'Part one of three of Pharrell William''s Human Race "Solar Pack," these come in a pink, bright blue and yellow colorway. Sporting a pink-based Primeknit upper, tribal graphic detailing, the phrase “MOTH3R” embroidered down the middle of the sneaker, a Boost cushioned midsole and yellow outsole. Their release date was on August of 2018, where they were available at select adidas Originals retailers worldwide for $250.', cost_price: 250, first_image_url: 'https://stockx-360.imgix.net/Adidas-NMD-Hu-Pharrell-Mother/Images/Adidas-NMD-Hu-Pharrell-Mother/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', second_image_url: 'https://stockx-360.imgix.net/Adidas-NMD-Hu-Pharrell-Mother/Images/Adidas-NMD-Hu-Pharrell-Mother/Lv2/img27.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', third_image_url: 'https://stockx-360.imgix.net/Adidas-NMD-Hu-Pharrell-Mother/Images/Adidas-NMD-Hu-Pharrell-Mother/Lv2/img18.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Adidas-NMD-Hu-Pharrell-Mother/Images/Adidas-NMD-Hu-Pharrell-Mother/Lv2/img09.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', brand_id: 1, size_id: 1, user_id: 2)
Shoe.create(name: 'Jordan 1 Retro High Satin Shattered Backboard (W)', color: 'BLACK/BLACK-STARFISH-SAIL', release_year: '2019', style: 'AV3725-010', description: 'Stay shining and saying “nice for what,” in these Air Jordan 1 Retro High Satin Shattered Backboards. This Air Jordan 1 Retro High OG was made exclusively for women, and was inspired by the men’s release from 2015, which came in the same black, starfish, and sail colorway. Only this time around they sport a satin upper with premium leather mid panels, an embroidered “Wings” logo on the collar and a full translucent orange outsole. These AJ1s dropped in May of 2018, where they were available at select Jordan Brand retailers worldwide for $160. If you’re a fan of the original Shattered Backboard AJ 1 and dig the satin update, you need to have this pair in your collection.', cost_price: 160, first_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-Satin-Shattered-Backboard-W/Images/Air-Jordan-1-Retro-High-Satin-Shattered-Backboard-W/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', second_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-Satin-Shattered-Backboard-W/Images/Air-Jordan-1-Retro-High-Satin-Shattered-Backboard-W/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', third_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-Satin-Shattered-Backboard-W/Images/Air-Jordan-1-Retro-High-Satin-Shattered-Backboard-W/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Air-Jordan-1-Retro-High-Satin-Shattered-Backboard-W/Images/Air-Jordan-1-Retro-High-Satin-Shattered-Backboard-W/Lv2/img16.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', brand_id: 2, size_id: 1, user_id: 2)
Shoe.create(name: 'Jordan 6 Retro Aleali May (W)', color: 'RUST PINK/BRIGHT CRIMSON', release_year: '2019', style: 'CI0550-600', description: 'Have you ever wanted a shoe that screams “Wow”? If so, cop the new Jordan 6 Retro Aleali May (W). This women’s AJ 6 sports a pink upper, red Jordan Jumpman, pink midsole, and a translucent sole. These sneakers released in March 2019 and retailed for $190. Add some rust pink drip to your sneaker collection today.', cost_price: 190, first_image_url: 'https://stockx-360.imgix.net/Air-Jordan-6-Retro-Aleali-May-W/Images/Air-Jordan-6-Retro-Aleali-May-W/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1552579808&w=1000', second_image_url: 'https://stockx-360.imgix.net/Air-Jordan-6-Retro-Aleali-May-W/Images/Air-Jordan-6-Retro-Aleali-May-W/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1552579808&w=1000', third_image_url: 'https://stockx-360.imgix.net/Air-Jordan-6-Retro-Aleali-May-W/Images/Air-Jordan-6-Retro-Aleali-May-W/Lv2/img18.jpg?auto=format,compress&q=90&updated_at=1552579808&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Air-Jordan-6-Retro-Aleali-May-W/Images/Air-Jordan-6-Retro-Aleali-May-W/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1552579808&w=1000', brand_id: 2, size_id: 1, user_id: 2)



Shoe.create(name: 'Jordan 1 Retro High Off-White White', color: 'WHITE/WHITE', release_year: '2018', style: 'AQ0818-100', description: 'Inspired by Air Jordan 1 colorways, the OFF-WHITE x Air Jordan 1 Retro High OG ''White'' 2018 is a reimagination of its ''Chicago''-themed predecessor. Designed by Virgil Abloh, the model features an all-white premium leather and mesh upper with deconstructed Swoosh branding and blue detailing, and Wings logos on the ankles. It is accented by black “AIR” lettering on the midsole, black ''Off-White™ for NIKE'' text on the side panels, and orange tabs.', cost_price: 190, first_image_url: 'https://stockx-360.imgix.net/air-jordan-1-retro-high-off-white-white_TruView/Images/air-jordan-1-retro-high-off-white-white_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', second_image_url: 'https://stockx-360.imgix.net/air-jordan-1-retro-high-off-white-white_TruView/Images/air-jordan-1-retro-high-off-white-white_TruView/Lv2/img23.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', third_image_url: 'https://stockx-360.imgix.net/air-jordan-1-retro-high-off-white-white_TruView/Images/air-jordan-1-retro-high-off-white-white_TruView/Lv2/img15.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/air-jordan-1-retro-high-off-white-white_TruView/Images/air-jordan-1-retro-high-off-white-white_TruView/Lv2/img09.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', brand_id: 2, size_id: 8, user_id: 3)
Shoe.create(name: 'adidas Pharrell NMD HU China Pack Happy (Gold) (Friends and Family)', color: 'GOLD/WHITE', release_year: '', style: 'F99762', description: 'Available exclusively in China at release...until now, the gold adidas Pharrell NMD HU China Pack Happy is a literal holy grail. One of four colorways in the China Pack, the happy version features white Boost midsoles, EVA insert overlays, lacing cage system and trail rubber outsoles to complete the design altogether. The right shoe features “Happy” in white lettering while the left shoe has the same word in Chinese lettering. This specific pair was limited to only 300 pairs. These dropped in May of 2018 and were only available at select adidas originals stores in China.', cost_price: 250, first_image_url: 'https://stockx-360.imgix.net/Adidas-Pharrell-NMD-HU-China-Pack-Happy-Gold/Images/Adidas-Pharrell-NMD-HU-China-Pack-Happy-Gold/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', second_image_url: 'https://stockx-360.imgix.net/Adidas-Pharrell-NMD-HU-China-Pack-Happy-Gold/Images/Adidas-Pharrell-NMD-HU-China-Pack-Happy-Gold/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', third_image_url: 'https://stockx-360.imgix.net/Adidas-Pharrell-NMD-HU-China-Pack-Happy-Gold/Images/Adidas-Pharrell-NMD-HU-China-Pack-Happy-Gold/Lv2/img16.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Adidas-Pharrell-NMD-HU-China-Pack-Happy-Gold/Images/Adidas-Pharrell-NMD-HU-China-Pack-Happy-Gold/Lv2/img11.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', brand_id: 1, size_id: 8, user_id: 3)
Shoe.create(name: 'Air Force 1 Low Off-White
', color: 'WHITE/WHITE-SAIL', release_year: '2017', style: 'AO4606-100', description: 'This Nike Air Force 1 Low was made in collaboration with Virgil Abloh''s Off-White imprint. A part of the "Ghosting" Series, this pair comes in a clean white and sail colorway. Sporting a reconstructed translucent upper, featuring a semi-revealing material to tie-in with the theme. Various materials are found throughout, as well as a red zip-tie and the words "Shoelaces" on the laces and "Air" on the translucent sole. Their release date was November 1st, 2017 where they were available alongside the rest of the Off-White x Nike "Ghosting" Collection. Retail for "The 10" Nike Air Force 1 Low was $170 and they were available in men''s sizing at select retailers worldwide.', cost_price: 170, first_image_url: 'https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Off-White/Images/Nike-Air-Force-1-Low-Off-White/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', second_image_url: 'https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Off-White/Images/Nike-Air-Force-1-Low-Off-White/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', third_image_url: 'https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Off-White/Images/Nike-Air-Force-1-Low-Off-White/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Nike-Air-Force-1-Low-Off-White/Images/Nike-Air-Force-1-Low-Off-White/Lv2/img12.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', brand_id: 13, size_id: 8, user_id: 3)
Shoe.create(name: 'Louis Vuitton LV Trainer Sneaker Boot High Black Grey', color: 'BLACK/GREY', release_year: '2019', style: '1A54IS', description: 'One of the standout looks of the Spring-Summer 2019 men''s show, the LV Trainer sneaker boot is an avant-garde hi-top crafted from black and gray calf leather. It features a padded collar and a velcro strap marked "Advanced Tech System". The Louis Vuitton signature on the side was hand-written by Artistic Director Virgil Abloh.', cost_price: 1600, first_image_url: 'https://stockx-360.imgix.net/Louis-Vuitton-LV-Trainer-Sneaker-Boot-High-Black-Grey/Images/Louis-Vuitton-LV-Trainer-Sneaker-Boot-High-Black-Grey/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1562620926&w=1000', second_image_url: 'https://stockx-360.imgix.net/Louis-Vuitton-LV-Trainer-Sneaker-Boot-High-Black-Grey/Images/Louis-Vuitton-LV-Trainer-Sneaker-Boot-High-Black-Grey/Lv2/img27.jpg?auto=format,compress&q=90&updated_at=1562620926&w=1000', third_image_url: 'https://stockx-360.imgix.net/Louis-Vuitton-LV-Trainer-Sneaker-Boot-High-Black-Grey/Images/Louis-Vuitton-LV-Trainer-Sneaker-Boot-High-Black-Grey/Lv2/img17.jpg?auto=format,compress&q=90&updated_at=1562620926&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Louis-Vuitton-LV-Trainer-Sneaker-Boot-High-Black-Grey/Images/Louis-Vuitton-LV-Trainer-Sneaker-Boot-High-Black-Grey/Lv2/img10.jpg?auto=format,compress&q=90&updated_at=1562620926&w=1000', brand_id: 11, size_id: 8, user_id: 3)
Shoe.create(name: 'Air Force 1 Low Crocodile Lux 25th Anniv', color: 'BAROQUE BROWN/BAROQUE BROWN-METALLIC GOLD', release_year: '2007', style: '315583-221', description: 'In 2007 the Nike Air Force 1 Crocodile Lux celebrated the AF1''s 25th anniversary with its Anaconda counterpart. It baffled many sneakerheads that this shoe simply showed up at retailers with a price of $2,000 -- to this day, the most expensive Nike shoe sold at retail. However, the shoe was deserving of its price tag. Crafted in Italy with plush Italian leather and real crocodile skin, this AF1 flaunts real gold lace dubraes and lace tips. The midsoles are wrapped in premium leather and the innards feature the same gorgeous, supple leather. Each box, with all accessories and shoes, weighs over six pounds and each pair of this AF1 is individually numbered beneath the tongue. This supremely luxurious Air Force One features a silver box (for the shoe''s silver anniversary) that reads "Air Force XXV," individual premium suede dustbags, cedar shoe trees, and a large, real gold hangtag with Bruce Kilgore''s signature on it. When Kilgore originally designed the AF1 in 1982, he never could have imagined how iconic and popular the Air Force One would become; it represented an entire era of sneakers, basketball, and hip hop. The Nike Air Force 1 Crocodile Lux is undoubtedly the most luxurious iteration of the classic silhouette.', cost_price: 2000, first_image_url: 'https://stockx-360.imgix.net/Nike-Air-Force-1-Crocodile-Lux-25-Anniversary/Images/Nike-Air-Force-1-Crocodile-Lux-25-Anniversary/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1560193361&w=1000', second_image_url: 'https://stockx-360.imgix.net/Nike-Air-Force-1-Crocodile-Lux-25-Anniversary/Images/Nike-Air-Force-1-Crocodile-Lux-25-Anniversary/Lv2/img28.jpg?auto=format,compress&q=90&updated_at=1560193361&w=1000', third_image_url: 'https://stockx-360.imgix.net/Nike-Air-Force-1-Crocodile-Lux-25-Anniversary/Images/Nike-Air-Force-1-Crocodile-Lux-25-Anniversary/Lv2/img19.jpg?auto=format,compress&q=90&updated_at=1560193361&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Nike-Air-Force-1-Crocodile-Lux-25-Anniversary/Images/Nike-Air-Force-1-Crocodile-Lux-25-Anniversary/Lv2/img12.jpg?auto=format,compress&q=90&updated_at=1560193361&w=1000', brand_id: 13, size_id: 8, user_id: 3)
Shoe.create(name: 'ASICS Gel-Lyte III Afew "Koi"
', color: 'RED/BLACK-WHITE', release_year: '2015', style: 'H51NK-0190', description: 'In 2015 German boutique Afew and Asics teamed up to create the truly special Asics Gel-Lyte III Afew Koi. Based in Düsseldorf, Afew went all out for this collab''s in-store release. The shoe dropped with a beautiful wooden bento box, a special booklet about the shoe, Afex x Asics chopsticks, co-branded dustbag, and two pairs of extra laces in Wasabi and Soy. The Asics GL3 Afew Koi represents the history of Japan Day and draws from the legendary Koi fish for inspiration. The Afew Koi featured premium suede all over the shoe in a few different colors; lush red suede hit the toeboxes and heels while off-white long-hair suede graces the side panels. The Afew crest is flaunted on the heels and unique photo-printed insoles while Afew and Japanese writing are featured patches on the heels. The white midsoles keep things classic but the translucent outsoles showcase beautiful details. The Asics Gel Lyte 3 Afew Koi utilizes Asics'' tried and true Gel cushioing within the midsole for a perfectly cushioed ride. The split tongue made this shoe a favorite for runners in the 90s and the setup still feels futuristic today. These get more and more comfortable with every wear so don''t be afraid to show them off.', cost_price: 170, first_image_url: 'https://stockx-360.imgix.net/Asics-Gel-Lyte-III-Afew-Koi_TruView/Images/Asics-Gel-Lyte-III-Afew-Koi_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', second_image_url: 'https://stockx-360.imgix.net/Asics-Gel-Lyte-III-Afew-Koi_TruView/Images/Asics-Gel-Lyte-III-Afew-Koi_TruView/Lv2/img20.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', third_image_url: 'https://stockx-360.imgix.net/Asics-Gel-Lyte-III-Afew-Koi_TruView/Images/Asics-Gel-Lyte-III-Afew-Koi_TruView/Lv2/img12.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', fourth_image_url: 'https://stockx-360.imgix.net/Asics-Gel-Lyte-III-Afew-Koi_TruView/Images/Asics-Gel-Lyte-III-Afew-Koi_TruView/Lv2/img11.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000', brand_id: 3, size_id: 8, user_id: 3)


UpcomingShoe.create(name: 'Nike AlphaDunk Dunk Of Death', image_url: 'http://4app.kicksonfire.com/kofapp/upload/events_master_images/thumb_ipad_6f453c64485abf86b080f4fd7b88cdd05d48c002f1a4f.jpg', release_date: '30/08/2019', retail_price: 170, brand_id: '13')
UpcomingShoe.create(name: 'Adidas D.O.N. Issue 1 Iron Spider', image_url: 'http://4app.kicksonfire.com/kofapp/upload/events_master_images/thumb_ipad_3ac1498ff36fc967bb2c05c522d577c85d250f32a487b.jpg', release_date: '31/08/2019', retail_price: 100, brand_id: '1')
UpcomingShoe.create(name: 'Titan X Nike LeBron 16 Low Agimat', image_url: 'http://4app.kicksonfire.com/kofapp/upload/events_master_images/thumb_ipad_ee16ca8236c3f968e3fa0b571de2b96c5d573f0fed1c0.jpg', release_date: '31/08/2019', retail_price: 175, brand_id: '13')
UpcomingShoe.create(name: 'Nike Signal D/MS/X Guava Ice', image_url: 'http://4app.kicksonfire.com/kofapp/upload/events_master_images/thumb_ipad_7db138a165fecb8ed6960159c97c7ace5d046e3b8e35c.jpg', release_date: '05/09/2019', retail_price: 130, brand_id: '13')
UpcomingShoe.create(name: 'Air Jordan 4 FIBA', image_url: 'http://4app.kicksonfire.com/kofapp/upload/events_master_images/thumb_ipad_eb3c5f7abfa14185b85fb9c8941a41c55d4dd115a4546.jpg', release_date: '07/09/2019', retail_price: 200, brand_id: '2')
UpcomingShoe.create(name: 'Nike Shox R4 Midnight Navy Metallic Silver', image_url: 'http://4app.kicksonfire.com/kofapp/upload/events_master_images/thumb_ipad_701a614b52d3a8f34da6f44a481244c75d09915d076ce.jpg', release_date: '07/09/2019', retail_price: 140, brand_id: '13')
UpcomingShoe.create(name: 'Travis Scott X Air Jordan 6 Medium Olive', image_url: 'http://4app.kicksonfire.com/kofapp/upload/events_master_images/thumb_ipad_2efb38d2ea7fc815f4dc6a7113ae7e595d421f526e4f4.jpg', release_date: '14/09/2019', retail_price: 250, brand_id: '2')
UpcomingShoe.create(name: 'Nike Air Barrage Mid White Laser Orange', image_url: 'http://4app.kicksonfire.com/kofapp/upload/events_master_images/thumb_ipad_3668e12acc858ce0d9084ae0206c72aa5d27ebf1d62df.jpg', release_date: '21/09/2019', retail_price: 150, brand_id: '13')



Blog.create(title: 'First Look at the Rumored Adidas UltraBOOST 2020', content: 'Although the hype surrounding adidas‘ UltraBOOST lineup has died down a bit since the silhouette’s inception, that hasn’t stopped the Germain giant in offering up new iterations of the beloved model.

After introducing the UltraBOOST ‘19 for this year, it looks as if a new version will soon be hitting the shelves. Shared via @sneakerprophet_, we have our first look at what could potentially be the UltraBOOST 2020. The sneaker seen above incorporates the same sleek design motif of the ‘19, however a few new details have been added such as the weave pattern on the Primeknit upper and taped Three Stripes cage. Additionally an iridescent “Metallic Purple” BOOST midsole finishes off the updated model. The pair also feature a co-branded tongue tab with ISS National Lab — a government-funded laboratory that aids in space research to improve life on Earth.

Keep it locked here for official imagery and a release date when they surface.

For sneakers you can purchase now, Stranger Things and Nike head back to the “Upside Down” in this week’s best footwear drops.
  ', image_url: 'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2019%2F08%2Fadidas-ultraboost-2020-first-look-001.jpg?q=90&w=1400&cbr=1&fit=max')

Blog.create(title: 'Anthony Van Engelen Receives New Signature Sneaker: Vans AVE Pro', content: 'After recently showcasing its patchwork-clad “MONALISA” pack, Vans has returned with a new special silhouette that celebrates Anthony Van Engelen‘s skateboarding career: Vans AVE Pro. It’s been nearly 15 years since Engelen released a signature cupsole model, and this one is the most technically advanced one yet.

The signature sneaker blends classic fabrics with functional textiles, utilizing a mix of LuxLiner™ mesh overlays and premium suede. Putting together details like crisp white laces, tonal rubber eyelets and black side stripes, the silhouette offers a clean and modern exterior that hides a bevy of advanced materials like Duracap™ underlays and RapidWeld™ no-sew technology.

Below the mesh uppers, light grey suede panels sit at the forefoot and the heel for added traction against grip tape. All of these features sit atop the progressive UltimateWaffle cupsole, equipped with an internal shank that enables flexibility around the forefoot. Another layer of impact cushions and a full-length Ultracush midsole round up the features of the sole.

In the development of the shoe, Van Engelen worked with Vans’ design team every step of the way, testing and reiterating until they came up with something worthy of the his name. Van Engelen mentioned in a statement, “with the AVE Pro — my first cupsole in 15 years — we achieved a completely transformed upper with Vans’ Rapidweld technology and improved the grip and board-feel in the sole overall. This shoe for me was a natural progression toward making a durable, technical skate shoe. Not only does it deliver a lighter, longer-lasting shoe for skating—but it’s an important step in innovation for Vans to pursue as the leader in skate shoes.”

The Vans AVE Pro will be available worldwide on August 22 at vans.com.', image_url: 'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2019%2F08%2Fvans-ave-pro-anthony-van-engelen-release-001.jpg?q=90&w=1400&cbr=1&fit=max')

Blog.create(title: 'A Closer Look at the UNDEFEATED x Nike Zoom Kobe 4 Protro Pack', content: 'To celebrate Kobe Bryant and all that is Mamba Day, UNDEFEATED and Nike have teamed up to release the Zoom Kobe 4 Protro Pack.

The range includes four different colorway options which presumably represent Team Kobe members DeMar DeRozan (“HYPER JADE”), Devin Booker (“TEAM ORANGE”), Kyle Kuzma (“COURT PURPLE”) and Giannis Antetokounmpo (“FIR”). “HYPER JADE” is decked out in teal with hits of orange; “TEAM ORANGE” is orange and purple; “COURT PURPLE” is purple and yellow; and finally “FIR” is green with white accents. Each model has been crafted from patent leather and features Kobe‘s soon-to-be-retired jersey numbers “8” and “24” debossed on the heels. UNDEFEATED’s Five Strikes logo comes in on the left tongue tab and can be seen in an iridescent shimmer printed on the lower back heels.

Each silhouette in the UNDEFEATED x Nike Zoom Kobe 4 Protro Pack will retail for $180 USD. The pack releases this Saturday, August 24 via raffle at each of UNDEFEATED’s chapter stores. Additionally a special range of co-branded basketball gear will also coincide with the sneaker release. An all-black basketball, shooting sleeves and duffle bag featuring iridescent Swoosh and Five Strike insignias, along with a mini basketball hoop and pump will be part of the lineup.

For more sneakers you can purchase now, Kanye serves up YEEZY 500s for the whole family in this week’s best footwear drops.
  ', image_url: 'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2019%2F08%2Fundefeated-nike-zoom-kobe-4-protro-pack-better-look-release-info-013.jpg?q=80&w=1000&cbr=1&fit=max')

Blog.create(title: 'NikeCourt Celebrates the Big Apple With the Air Zoom Vapor X Kyrie 5 "NYC"', content: 'With the 2019 US Open right around the corner, NikeCourt recently put together an “NYC”-inspired colorway of the Air Zoom Vapor X Kyrie 5.

Revisiting the hybrid silhouette which mashes elements of tennis player Nick Kyrgios and basketball player Kyrie Irving‘s signature shoes, the latest take is centered around graffiti-inspired details. Dressed in a bold color scheme made up of purple and black, the New York homage sports vibrant volt midfoot Swooshes and “NYC” prints around the toe region. Additional details include torn-poster graphics on the toe bumpers and a marbled toe caps.

The NikeCourt Air Zoom Vapor X Kyrie 5 “NYC” is set to release globally on nike.com and select locations August 24.', image_url: 'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2019%2F08%2Fnikecourt-air-zoom-vapor-x-kyrie-5-nyc-release-1.jpg?q=90&w=1400&cbr=1&fit=max')

Blog.create(title: 'Burberry Hiking Boot Gets Signature Check Update & Sturdy Rugged Soles', content: 'Fresh from the release of its check-covered low-top sneakers, Burberry has now dropped a pair of Brown Tor Vintage Check Hiking Boots as we gear up for Fall/Winter 2019.

The Riccardo Tisci-designed boots feature a mixture of checkered cloth, suede, leather and rubber panels on its upper. Tanned brown leather is used to construct the supportive areas such as the toe box and heel section, while darker brown suede is used for the vamp and forefoot. The archetype check design is used for the mid-panel, and a contrasting touch of black perforated leather has been added around the collar.

Burberry’s hiking boot is covered in premium details such as metal lace loops and rivets lining the tongue — which sports a rubberized Burberry plaque at the top — while the recently introduced “TB” Thomas Burberry logo has been added to the rear-quarter at the heel in white for more contrasting elements. The boot sits atop a chunky rubber sole unit, which also features “TB” and Burberry branding, and is finished with a hiking rope lace system and a yellow leather lining.

You can pick up a pair of the Burberry Tor Vintage Check Hiking Boots from retailers such as Browns now for $890 USD.', image_url: 'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2019%2F08%2Fburberry-brown-tor-vintage-check-hiking-boots-release-information-1.jpg?q=90&w=1400&cbr=1&fit=max')
Blog.create(title: 'size? and Vans Stitch Together Third Patchwork Sneaker Collaboration', content: 'Though size? has kept busy with frequent adidas collaborations, its joint efforts with Vans remain longstanding fan favorites. Thus, sneakerheads should rejoice at the news that the Manchester-based boutique has rejoined the California-based sneaker brand for “Patchwork III,” the pair’s third mismatched silhouette.

This time, the Bold Ni is the model of choice, sporting a monochrome patchwork makeover that highlights its asymmetric detailing. Like the Old Skool “Factory Floor,” size?’s latest collaborative silhouette takes cues from excess scraps found throughout Vans’ Anaheim factory.

Over a dozen different textiles appear across the sleek shoe, intentionally mismatching the various pony hair, checkerboard, camo, polka dots, denim and suede seen throughout. Uneven foxing tape and touches of transparent TPU keep the dynamic design feeling fresh, with an UltraCush Lite sockliner for heightened comfort.

Expect the collaborative Vans Bold Ni silhouette to hit size?’s web store and app on August 30.', image_url: 'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2019%2F08%2Fsize-vans-bold-ni-patchwork-black-white-asymmetric-collab1.jpg?q=90&w=1400&cbr=1&fit=max')
Blog.create(title: 'A Closer Look at FILA''s Disruptor 2 "Zebra" and Nike''s "Crimson/Gold" Air Max 200', content: 'As the latest additions to Bloomingdale’s impressive selection of sneakers, the FILA Disruptor 2 Premium “Zebra” and Nike Air Max 200 cater to footwear enthusiasts with bold personal style. With their graphic yet distinct details, the offerings represent the breadth of noteworthy shoes available from the retailer.

The Nike Air Max 200 is the newest member of the Air Max family, notable for its visible air and updated cushioning. Though the midsole and heel bubble are similar to the Air Max 180, a reimagined upper sets the shoe apart from its predecessors. On this version, the black and white upper is brightened with hits of layered suede panels in “Bright Crimson,” “University Gold” and green, as well as a gradient Air 200 logo on the tongue.

For its exclusive women’s offerings, Bloomingdale’s adds the FILA Disruptor 2 Premium, reimagined in a zebra print pony hair — a bold update to the brand’s already popular chunky-soled silhouette. Having originally been released in 1996, the model has re-established itself as a wardrobe staple in the contemporary. Rounding out the shoe is its signature sawtooth rubber outsole and the FILA logo hitting the shoe’s tongue, quarter, midsole and back counter.', image_url: 'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2019%2F08%2Fbloomingdales-fila-disruptor-zebra-nike-slam-dunk-vandalised-4.jpg?q=90&w=1400&cbr=1&fit=max')
Blog.create(title: 'AFEW & Diadora''s N.9000 "Highly Addictive" Will Be Limited to Just 50 Pairs', content: 'AFEW and Diadora are coming together once again for the release of the N.9000 “Highly Addictive.” The highly-limited pair pays homage to 2017’s V.7000 “Highly Addictive,” a pair that is highly sought-after on the resell market nowadays.

The N.9000 iteration by AFEW and Diadora sports the same light green, pale red and off-white color scheme as the V.7000, and is made from premium kangaroo leather upper in Italy. AFEW, “NYC,” “DUS” and Diadora branding in tonal colors decorate the sneaker’s immaculate upper, which draws inspiration from New York City’s heavy use of raw concrete for darker overlaying sections.

Attention to detail was key in the making of this rare sneaker, as AFEW and Diadora round off the design with a leather lining, pill-printed insoles and beautifully supple leather throughout. Embroidered tongues sport the Diadora moniker, while the heel tabs are given laser-etched pill motifs taken from the V.7000.

The AFEW x Diadora N.9000 “Highly Addictive” will be limited to just 50 units — similar to the Friends and Family V.7000 — and will be sold exclusively in-store at Sneakersnstuff New York for $230 USD on September 7. Take a closer look at the highly-anticipated pair above.', image_url: 'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2019%2F08%2Fafew-diadora-highly-addictive-n-9000-sneaker-release-information-sneakersnstuff-nyc-1.jpg?q=90&w=1400&cbr=1&fit=max')
Blog.create(title: 'Liam Gallagher & adidas Spezial Unveil Minimalistic Padiham LG SPZL', content: 'adidas Originals and Liam Gallagher have debuted their upcoming collaborative Spezial silhouette, the Padiham LG SPZL.

The minimalist sneaker will release alongside Gallagher’s upcoming album, Why Me? Why Not?, and was previously spotted on foot of the former Oasis frontman at an exclusive gig in London back in June. Today, adidas Originals offers a first look at the duo’s offering, which sports a clean cream suede and leather upper alongside a matching low-profile sole unit.

Gallagher and the Spezial team drew inspiration from the original Padiham SPZL, a silhouette inspired by a vintage adidas style unearthed by Gary Aspden. Using this as a base, the team made the sneaker more neutral and understated. Other features of the design include gold foil branding, a zig-zag cut eyestay, zig-zag leather Three Stripes, and a gum sole unit finished in cream. To rework the original Padiham SPZL’s design, a new tongue featuring Liam Gallagher’s face and dual branding has also been added.

The collaborative pair is a nod to Liam Gallagher’s affinity for adidas, which he wore “religiously” when growing up. Gallagher says that the collaboration with Spezial came about because he “wears the clobber and it’s cool like me.”

Gary Aspden says, “I have known Liam for over 20 years and we have always got on. He is one of the people who have worn and supported what we do with adidas Spezial since day one so this collaboration evolved organically.”

Aspden added, “We made a few tweaks to the upper pattern along with a different tongue — as anyone who is a fan of gum soled, suede adidas trainers, knows it is all about those subtle details. Liam gave comments on each sample until the final version which we held off on showing him until we presented them to him for the first time backstage at his gig in Hackney. We filmed that moment as we wanted to capture his honest reaction. Anyone who has worn the Three Stripes loyally for as long as he has will understand that excitement.”

Pick up a pair of the limited-edition Liam Gallagher x adidas Spezial Padiham LG SPZL at adidas Originals stores and online on August 30.', image_url: 'https://image-cdn.hypb.st/https%3A%2F%2Fhypebeast.com%2Fimage%2F2019%2F08%2Fadidas-originals-spezial-liam-gallagher-padiham-lg-spzl-release-information-1.jpg?q=90&w=1400&cbr=1&fit=max')